### ISSUE TITLE
Support Kubernetes version 1.23

### ISSUE THREAD

**Issue by jaxesn** [aws/eks-anywhere#2159]
**What would you like to be added**:
EKS-D is working on a future release with 1.23 support.  Integrate into eks-a and eks-a-build-tooling.
**Tasks**:

- [x] Create resources in CDK
- [x] Release dev build support
- [x] Add support for 1-23 with feature flag
- [x] 1.23 vsphere cluster creation (Ubuntu), run sonobuoy tests
- [x] Modify existing Ubuntu tests to use 1.23
- [x] Build BR ovas, cluster creation with those OVAs
- [x] Import OVAs once ready
- [x] 1.23 vsphere cluster creation (Bottlerocket), run sonobuoy tests
- [x] Modify BR tests to use 1.23
- [ ] Update default CLI to use 1.23
- [ ] Update docs
