### ISSUE TITLE
Embed EKS Distro manifests in eksa-controller-manager

### ISSUE THREAD

**Issue by abhinavmpandey08** [aws/eks-anywhere#410]
**What would you like to be added**:
Embed eks-distro manifest in eksa-controller-manager so it doesn't try it to pull it dynamically

**Why is this needed**:
Currently `eksa-controller-manager` pulls eks-distro manifest which requires access to the internet. It would be nice to have to embedded in the controller so it won't need to pull it during runtime. This will eventually be needed for air-gapped support

-------------------
Design doc: #1162 

- [x] Update EKS-D bundle with new fields #1198 
- [x] Add `eksdReleaseRef` to cluster status #1217 
- [x] Add tasks during create & upgrade to install EKS-D components #1391
